//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Dto_EmptySerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Dto.Empty> {
        
        private MsgPack.Serialization.MessagePackSerializer<bool> _serializer0;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Dto.Empty>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.Empty>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Dto.Empty, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Dto.Empty, bool> this_SetUnpackedValueOfvalueDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, bool> MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>> _unpackOperationTable;
        
        public Stormancer_Dto_EmptySerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<bool>(schema0);
            System.Action<MsgPack.Packer, Stormancer.Dto.Empty>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Dto.Empty>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Dto.Empty>[1];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Dto.Empty>(this.PackValueOfvalue);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.Empty>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.Empty>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.Empty>>(1);
            packOperationTable["value"] = new System.Action<MsgPack.Packer, Stormancer.Dto.Empty>(this.PackValueOfvalue);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Dto.Empty, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Dto.Empty, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Dto.Empty, bool>>(0);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>[1];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>(this.UnpackValueOfvalue);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>>(1);
            unpackOperationTable["value"] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.Empty, int, int>(this.UnpackValueOfvalue);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "value"};
            this.this_SetUnpackedValueOfvalueDelegate = new System.Action<Stormancer.Dto.Empty, bool>(this.SetUnpackedValueOfvalue);
            this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, bool>(MsgPack.Serialization.UnpackHelpers.UnpackBooleanValue);
        }
        
        private void PackValueOfvalue(MsgPack.Packer packer, Stormancer.Dto.Empty objectTree) {
            this._serializer0.PackTo(packer, objectTree.value);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Dto.Empty objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Dto.Empty> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Dto.Empty>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Dto.Empty> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Dto.Empty>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfvalue(Stormancer.Dto.Empty unpackingContext, bool unpackedValue) {
            unpackingContext.value = unpackedValue;
        }
        
        private void UnpackValueOfvalue(MsgPack.Unpacker unpacker, Stormancer.Dto.Empty unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Dto.Empty, bool> unpackHelperParameters = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Dto.Empty, bool>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(bool);
            unpackHelperParameters.MemberName = "value";
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfvalueDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters);
        }
        
        protected internal override Stormancer.Dto.Empty UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Dto.Empty result = default(Stormancer.Dto.Empty);
            result = new Stormancer.Dto.Empty();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Dto.Empty>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Dto.Empty>(), this._unpackOperationTable);
            }
        }
    }
}

