//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_LeaderboardOrderingSerializer : MsgPack.Serialization.EnumMessagePackSerializer<Stormancer.Plugins.LeaderboardOrdering> {
        
        public Stormancer_Plugins_LeaderboardOrderingSerializer(MsgPack.Serialization.SerializationContext context) : 
                this(context, MsgPack.Serialization.EnumSerializationMethod.ByName) {
        }
        
        public Stormancer_Plugins_LeaderboardOrderingSerializer(MsgPack.Serialization.SerializationContext context, MsgPack.Serialization.EnumSerializationMethod enumSerializationMethod) : 
                base(context, enumSerializationMethod) {
        }
        
        protected internal override void PackUnderlyingValueTo(MsgPack.Packer packer, Stormancer.Plugins.LeaderboardOrdering enumValue) {
            packer.Pack(((byte)(enumValue)));
        }
        
        protected internal override Stormancer.Plugins.LeaderboardOrdering UnpackFromUnderlyingValue(MsgPack.MessagePackObject messagePackObject) {
            return ((Stormancer.Plugins.LeaderboardOrdering)(messagePackObject.AsByte()));
        }
    }
}

