//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_PlayerProfileSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.PlayerProfile> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.PlayerProfile, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.PlayerProfile, string> this_SetUnpackedValueOfIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.PlayerProfile, string> this_SetUnpackedValueOfPlayerIdDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_PlayerProfileSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>[2];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>(this.PackValueOfId);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>(this.PackValueOfPlayerId);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>>(2);
            packOperationTable["Id"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>(this.PackValueOfId);
            packOperationTable["PlayerId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.PlayerProfile>(this.PackValueOfPlayerId);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.PlayerProfile, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.PlayerProfile, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.PlayerProfile, bool>>(2);
            nullCheckerTable["Id"] = new System.Func<Stormancer.Plugins.PlayerProfile, bool>(this.IsIdNull);
            nullCheckerTable["PlayerId"] = new System.Func<Stormancer.Plugins.PlayerProfile, bool>(this.IsPlayerIdNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>[2];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>(this.UnpackValueOfId);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>(this.UnpackValueOfPlayerId);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>>(2);
            unpackOperationTable["Id"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>(this.UnpackValueOfId);
            unpackOperationTable["PlayerId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.PlayerProfile, int, int>(this.UnpackValueOfPlayerId);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "Id",
                    "PlayerId"};
            this.this_SetUnpackedValueOfIdDelegate = new System.Action<Stormancer.Plugins.PlayerProfile, string>(this.SetUnpackedValueOfId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfPlayerIdDelegate = new System.Action<Stormancer.Plugins.PlayerProfile, string>(this.SetUnpackedValueOfPlayerId);
        }
        
        private void PackValueOfId(MsgPack.Packer packer, Stormancer.Plugins.PlayerProfile objectTree) {
            this._serializer0.PackTo(packer, objectTree.Id);
        }
        
        private bool IsIdNull(Stormancer.Plugins.PlayerProfile objectTree) {
            return (objectTree.Id == null);
        }
        
        private void PackValueOfPlayerId(MsgPack.Packer packer, Stormancer.Plugins.PlayerProfile objectTree) {
            this._serializer0.PackTo(packer, objectTree.PlayerId);
        }
        
        private bool IsPlayerIdNull(Stormancer.Plugins.PlayerProfile objectTree) {
            return (objectTree.PlayerId == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.PlayerProfile objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.PlayerProfile> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.PlayerProfile>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.PlayerProfile> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.PlayerProfile>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfId(Stormancer.Plugins.PlayerProfile unpackingContext, string unpackedValue) {
            unpackingContext.Id = unpackedValue;
        }
        
        private void UnpackValueOfId(MsgPack.Unpacker unpacker, Stormancer.Plugins.PlayerProfile unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.PlayerProfile, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.PlayerProfile, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "Id";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfPlayerId(Stormancer.Plugins.PlayerProfile unpackingContext, string unpackedValue) {
            unpackingContext.PlayerId = unpackedValue;
        }
        
        private void UnpackValueOfPlayerId(MsgPack.Unpacker unpacker, Stormancer.Plugins.PlayerProfile unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.PlayerProfile, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.PlayerProfile, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer0;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "PlayerId";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfPlayerIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        protected internal override Stormancer.Plugins.PlayerProfile UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.PlayerProfile result = default(Stormancer.Plugins.PlayerProfile);
            result = new Stormancer.Plugins.PlayerProfile();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.PlayerProfile>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.PlayerProfile>(), this._unpackOperationTable);
            }
        }
    }
}

