//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_PlayerSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.Player> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.Player>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Player>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.Player, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.Player, string> this_SetUnpackedValueOfPlayerIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.Player, string> this_SetUnpackedValueOfPseudoDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_PlayerSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            System.Action<MsgPack.Packer, Stormancer.Plugins.Player>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.Player>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.Player>[2];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Player>(this.PackValueOfPlayerId);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Player>(this.PackValueOfPseudo);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Player>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Player>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Player>>(2);
            packOperationTable["PlayerId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Player>(this.PackValueOfPlayerId);
            packOperationTable["Pseudo"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Player>(this.PackValueOfPseudo);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.Player, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.Player, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.Player, bool>>(2);
            nullCheckerTable["PlayerId"] = new System.Func<Stormancer.Plugins.Player, bool>(this.IsPlayerIdNull);
            nullCheckerTable["Pseudo"] = new System.Func<Stormancer.Plugins.Player, bool>(this.IsPseudoNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>[2];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>(this.UnpackValueOfPlayerId);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>(this.UnpackValueOfPseudo);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>>(2);
            unpackOperationTable["PlayerId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>(this.UnpackValueOfPlayerId);
            unpackOperationTable["Pseudo"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Player, int, int>(this.UnpackValueOfPseudo);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "PlayerId",
                    "Pseudo"};
            this.this_SetUnpackedValueOfPlayerIdDelegate = new System.Action<Stormancer.Plugins.Player, string>(this.SetUnpackedValueOfPlayerId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfPseudoDelegate = new System.Action<Stormancer.Plugins.Player, string>(this.SetUnpackedValueOfPseudo);
        }
        
        private void PackValueOfPlayerId(MsgPack.Packer packer, Stormancer.Plugins.Player objectTree) {
            this._serializer0.PackTo(packer, objectTree.PlayerId);
        }
        
        private bool IsPlayerIdNull(Stormancer.Plugins.Player objectTree) {
            return (objectTree.PlayerId == null);
        }
        
        private void PackValueOfPseudo(MsgPack.Packer packer, Stormancer.Plugins.Player objectTree) {
            this._serializer0.PackTo(packer, objectTree.Pseudo);
        }
        
        private bool IsPseudoNull(Stormancer.Plugins.Player objectTree) {
            return (objectTree.Pseudo == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.Player objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.Player> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.Player>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.Player> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.Player>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfPlayerId(Stormancer.Plugins.Player unpackingContext, string unpackedValue) {
            unpackingContext.PlayerId = unpackedValue;
        }
        
        private void UnpackValueOfPlayerId(MsgPack.Unpacker unpacker, Stormancer.Plugins.Player unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Player, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Player, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "PlayerId";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfPlayerIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfPseudo(Stormancer.Plugins.Player unpackingContext, string unpackedValue) {
            unpackingContext.Pseudo = unpackedValue;
        }
        
        private void UnpackValueOfPseudo(MsgPack.Unpacker unpacker, Stormancer.Plugins.Player unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Player, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Player, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer0;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "Pseudo";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfPseudoDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        protected internal override Stormancer.Plugins.Player UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.Player result = default(Stormancer.Plugins.Player);
            result = new Stormancer.Plugins.Player();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.Player>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.Player>(), this._unpackOperationTable);
            }
        }
    }
}

