//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_GameResultSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.GameResult> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<bool> _serializer1;
        
        private MsgPack.Serialization.MessagePackSerializer<System.Collections.Generic.List<Stormancer.Plugins.SetResult>> _serializer2;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.GameResult, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.GameResult, string> this_SetUnpackedValueOfWinnerIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.GameResult, bool> this_SetUnpackedValueOfForfaitDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, bool> MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
        
        private System.Action<Stormancer.Plugins.GameResult, System.Collections.Generic.List<Stormancer.Plugins.SetResult>> this_SetUnpackedValueOfSetsDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_GameResultSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<bool>(schema1);
            MsgPack.Serialization.PolymorphismSchema schema2 = default(MsgPack.Serialization.PolymorphismSchema);
            schema2 = null;
            this._serializer2 = context.GetSerializer<System.Collections.Generic.List<Stormancer.Plugins.SetResult>>(schema2);
            System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>[3];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>(this.PackValueOfWinnerId);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>(this.PackValueOfForfait);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>(this.PackValueOfSets);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>>(3);
            packOperationTable["WinnerId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>(this.PackValueOfWinnerId);
            packOperationTable["Forfait"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>(this.PackValueOfForfait);
            packOperationTable["Sets"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameResult>(this.PackValueOfSets);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameResult, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameResult, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameResult, bool>>(2);
            nullCheckerTable["WinnerId"] = new System.Func<Stormancer.Plugins.GameResult, bool>(this.IsWinnerIdNull);
            nullCheckerTable["Sets"] = new System.Func<Stormancer.Plugins.GameResult, bool>(this.IsSetsNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>[3];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>(this.UnpackValueOfWinnerId);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>(this.UnpackValueOfForfait);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>(this.UnpackValueOfSets);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>>(3);
            unpackOperationTable["WinnerId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>(this.UnpackValueOfWinnerId);
            unpackOperationTable["Forfait"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>(this.UnpackValueOfForfait);
            unpackOperationTable["Sets"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameResult, int, int>(this.UnpackValueOfSets);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "WinnerId",
                    "Forfait",
                    "Sets"};
            this.this_SetUnpackedValueOfWinnerIdDelegate = new System.Action<Stormancer.Plugins.GameResult, string>(this.SetUnpackedValueOfWinnerId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfForfaitDelegate = new System.Action<Stormancer.Plugins.GameResult, bool>(this.SetUnpackedValueOfForfait);
            this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, bool>(MsgPack.Serialization.UnpackHelpers.UnpackBooleanValue);
            this.this_SetUnpackedValueOfSetsDelegate = new System.Action<Stormancer.Plugins.GameResult, System.Collections.Generic.List<Stormancer.Plugins.SetResult>>(this.SetUnpackedValueOfSets);
        }
        
        private void PackValueOfWinnerId(MsgPack.Packer packer, Stormancer.Plugins.GameResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.WinnerId);
        }
        
        private bool IsWinnerIdNull(Stormancer.Plugins.GameResult objectTree) {
            return (objectTree.WinnerId == null);
        }
        
        private void PackValueOfForfait(MsgPack.Packer packer, Stormancer.Plugins.GameResult objectTree) {
            this._serializer1.PackTo(packer, objectTree.Forfait);
        }
        
        private void PackValueOfSets(MsgPack.Packer packer, Stormancer.Plugins.GameResult objectTree) {
            this._serializer2.PackTo(packer, objectTree.Sets);
        }
        
        private bool IsSetsNull(Stormancer.Plugins.GameResult objectTree) {
            return (objectTree.Sets == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.GameResult objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.GameResult> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.GameResult>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.GameResult> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.GameResult>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfWinnerId(Stormancer.Plugins.GameResult unpackingContext, string unpackedValue) {
            unpackingContext.WinnerId = unpackedValue;
        }
        
        private void UnpackValueOfWinnerId(MsgPack.Unpacker unpacker, Stormancer.Plugins.GameResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameResult, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameResult, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "WinnerId";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfWinnerIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfForfait(Stormancer.Plugins.GameResult unpackingContext, bool unpackedValue) {
            unpackingContext.Forfait = unpackedValue;
        }
        
        private void UnpackValueOfForfait(MsgPack.Unpacker unpacker, Stormancer.Plugins.GameResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.GameResult, bool> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.GameResult, bool>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(bool);
            unpackHelperParameters0.MemberName = "Forfait";
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfForfaitDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfSets(Stormancer.Plugins.GameResult unpackingContext, System.Collections.Generic.List<Stormancer.Plugins.SetResult> unpackedValue) {
            unpackingContext.Sets = unpackedValue;
        }
        
        private void UnpackValueOfSets(MsgPack.Unpacker unpacker, Stormancer.Plugins.GameResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameResult, System.Collections.Generic.List<Stormancer.Plugins.SetResult>> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameResult, System.Collections.Generic.List<Stormancer.Plugins.SetResult>>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer2;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(System.Collections.Generic.List<Stormancer.Plugins.SetResult>);
            unpackHelperParameters1.MemberName = "Sets";
            unpackHelperParameters1.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters1.DirectRead = null;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfSetsDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters1);
        }
        
        protected internal override Stormancer.Plugins.GameResult UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.GameResult result = default(Stormancer.Plugins.GameResult);
            result = new Stormancer.Plugins.GameResult();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.GameResult>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.GameResult>(), this._unpackOperationTable);
            }
        }
    }
}

