//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_GameFinderParametersSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.GameFinderParameters> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.GameFinderParameters, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.GameFinderParameters, string> this_SetUnpackedValueOfGameIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_GameFinderParametersSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>[1];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>(this.PackValueOfGameId);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>>(1);
            packOperationTable["GameId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderParameters>(this.PackValueOfGameId);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameFinderParameters, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameFinderParameters, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameFinderParameters, bool>>(1);
            nullCheckerTable["GameId"] = new System.Func<Stormancer.Plugins.GameFinderParameters, bool>(this.IsGameIdNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>[1];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>(this.UnpackValueOfGameId);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>>(1);
            unpackOperationTable["GameId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderParameters, int, int>(this.UnpackValueOfGameId);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "GameId"};
            this.this_SetUnpackedValueOfGameIdDelegate = new System.Action<Stormancer.Plugins.GameFinderParameters, string>(this.SetUnpackedValueOfGameId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
        }
        
        private void PackValueOfGameId(MsgPack.Packer packer, Stormancer.Plugins.GameFinderParameters objectTree) {
            this._serializer0.PackTo(packer, objectTree.GameId);
        }
        
        private bool IsGameIdNull(Stormancer.Plugins.GameFinderParameters objectTree) {
            return (objectTree.GameId == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.GameFinderParameters objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.GameFinderParameters> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.GameFinderParameters>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.GameFinderParameters> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.GameFinderParameters>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfGameId(Stormancer.Plugins.GameFinderParameters unpackingContext, string unpackedValue) {
            unpackingContext.GameId = unpackedValue;
        }
        
        private void UnpackValueOfGameId(MsgPack.Unpacker unpacker, Stormancer.Plugins.GameFinderParameters unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameFinderParameters, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameFinderParameters, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "GameId";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfGameIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        protected internal override Stormancer.Plugins.GameFinderParameters UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.GameFinderParameters result = default(Stormancer.Plugins.GameFinderParameters);
            result = new Stormancer.Plugins.GameFinderParameters();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.GameFinderParameters>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.GameFinderParameters>(), this._unpackOperationTable);
            }
        }
    }
}

