//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_LoginResultSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.LoginResult> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<bool> _serializer1;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.LoginResult, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.LoginResult, string> this_SetUnpackedValueOfErrorMsgDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.LoginResult, bool> this_SetUnpackedValueOfSuccessDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, bool> MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
        
        private System.Action<Stormancer.Plugins.LoginResult, string> this_SetUnpackedValueOfUserIdDelegate;
        
        private System.Action<Stormancer.Plugins.LoginResult, string> this_SetUnpackedValueOfUserNameDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_LoginResultSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<bool>(schema1);
            System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>[4];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfErrorMsg);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfSuccess);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfUserId);
            packOperationList[3] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfUserName);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>>(4);
            packOperationTable["ErrorMsg"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfErrorMsg);
            packOperationTable["Success"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfSuccess);
            packOperationTable["UserId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfUserId);
            packOperationTable["UserName"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LoginResult>(this.PackValueOfUserName);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.LoginResult, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.LoginResult, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.LoginResult, bool>>(3);
            nullCheckerTable["ErrorMsg"] = new System.Func<Stormancer.Plugins.LoginResult, bool>(this.IsErrorMsgNull);
            nullCheckerTable["UserId"] = new System.Func<Stormancer.Plugins.LoginResult, bool>(this.IsUserIdNull);
            nullCheckerTable["UserName"] = new System.Func<Stormancer.Plugins.LoginResult, bool>(this.IsUserNameNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>[4];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfErrorMsg);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfSuccess);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfUserId);
            unpackOperationList[3] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfUserName);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>>(4);
            unpackOperationTable["ErrorMsg"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfErrorMsg);
            unpackOperationTable["Success"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfSuccess);
            unpackOperationTable["UserId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfUserId);
            unpackOperationTable["UserName"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LoginResult, int, int>(this.UnpackValueOfUserName);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "ErrorMsg",
                    "Success",
                    "UserId",
                    "UserName"};
            this.this_SetUnpackedValueOfErrorMsgDelegate = new System.Action<Stormancer.Plugins.LoginResult, string>(this.SetUnpackedValueOfErrorMsg);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfSuccessDelegate = new System.Action<Stormancer.Plugins.LoginResult, bool>(this.SetUnpackedValueOfSuccess);
            this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, bool>(MsgPack.Serialization.UnpackHelpers.UnpackBooleanValue);
            this.this_SetUnpackedValueOfUserIdDelegate = new System.Action<Stormancer.Plugins.LoginResult, string>(this.SetUnpackedValueOfUserId);
            this.this_SetUnpackedValueOfUserNameDelegate = new System.Action<Stormancer.Plugins.LoginResult, string>(this.SetUnpackedValueOfUserName);
        }
        
        private void PackValueOfErrorMsg(MsgPack.Packer packer, Stormancer.Plugins.LoginResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.ErrorMsg);
        }
        
        private bool IsErrorMsgNull(Stormancer.Plugins.LoginResult objectTree) {
            return (objectTree.ErrorMsg == null);
        }
        
        private void PackValueOfSuccess(MsgPack.Packer packer, Stormancer.Plugins.LoginResult objectTree) {
            this._serializer1.PackTo(packer, objectTree.Success);
        }
        
        private void PackValueOfUserId(MsgPack.Packer packer, Stormancer.Plugins.LoginResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.UserId);
        }
        
        private bool IsUserIdNull(Stormancer.Plugins.LoginResult objectTree) {
            return (objectTree.UserId == null);
        }
        
        private void PackValueOfUserName(MsgPack.Packer packer, Stormancer.Plugins.LoginResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.UserName);
        }
        
        private bool IsUserNameNull(Stormancer.Plugins.LoginResult objectTree) {
            return (objectTree.UserName == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.LoginResult objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.LoginResult> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.LoginResult>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.LoginResult> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.LoginResult>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfErrorMsg(Stormancer.Plugins.LoginResult unpackingContext, string unpackedValue) {
            unpackingContext.ErrorMsg = unpackedValue;
        }
        
        private void UnpackValueOfErrorMsg(MsgPack.Unpacker unpacker, Stormancer.Plugins.LoginResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LoginResult, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LoginResult, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "ErrorMsg";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfErrorMsgDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfSuccess(Stormancer.Plugins.LoginResult unpackingContext, bool unpackedValue) {
            unpackingContext.Success = unpackedValue;
        }
        
        private void UnpackValueOfSuccess(MsgPack.Unpacker unpacker, Stormancer.Plugins.LoginResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.LoginResult, bool> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.LoginResult, bool>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(bool);
            unpackHelperParameters0.MemberName = "Success";
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfSuccessDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfUserId(Stormancer.Plugins.LoginResult unpackingContext, string unpackedValue) {
            unpackingContext.UserId = unpackedValue;
        }
        
        private void UnpackValueOfUserId(MsgPack.Unpacker unpacker, Stormancer.Plugins.LoginResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LoginResult, string> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LoginResult, string>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer0;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(string);
            unpackHelperParameters1.MemberName = "UserId";
            unpackHelperParameters1.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters1.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfUserIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters1);
        }
        
        private void SetUnpackedValueOfUserName(Stormancer.Plugins.LoginResult unpackingContext, string unpackedValue) {
            unpackingContext.UserName = unpackedValue;
        }
        
        private void UnpackValueOfUserName(MsgPack.Unpacker unpacker, Stormancer.Plugins.LoginResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LoginResult, string> unpackHelperParameters2 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LoginResult, string>);
            unpackHelperParameters2.Unpacker = unpacker;
            unpackHelperParameters2.UnpackingContext = unpackingContext;
            unpackHelperParameters2.Serializer = this._serializer0;
            unpackHelperParameters2.ItemsCount = itemsCount;
            unpackHelperParameters2.Unpacked = indexOfItem;
            unpackHelperParameters2.TargetObjectType = typeof(string);
            unpackHelperParameters2.MemberName = "UserName";
            unpackHelperParameters2.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters2.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters2.Setter = this.this_SetUnpackedValueOfUserNameDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters2);
        }
        
        protected internal override Stormancer.Plugins.LoginResult UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.LoginResult result = default(Stormancer.Plugins.LoginResult);
            result = new Stormancer.Plugins.LoginResult();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.LoginResult>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.LoginResult>(), this._unpackOperationTable);
            }
        }
    }
}

