//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Dto_RouteDtoSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Dto.RouteDto> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<ushort> _serializer1;
        
        private MsgPack.Serialization.MessagePackSerializer<System.Collections.Generic.Dictionary<string, string>> _serializer2;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Dto.RouteDto, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Dto.RouteDto, string> this_SetUnpackedValueOfNameDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Dto.RouteDto, ushort> this_SetUnpackedValueOfHandleDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, ushort> MsgPack_Serialization_UnpackHelpers_UnpackUInt16ValueDelegate;
        
        private System.Action<Stormancer.Dto.RouteDto, System.Collections.Generic.Dictionary<string, string>> this_SetUnpackedValueOfMetadataDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>> _unpackOperationTable;
        
        public Stormancer_Dto_RouteDtoSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<ushort>(schema1);
            MsgPack.Serialization.PolymorphismSchema schema2 = default(MsgPack.Serialization.PolymorphismSchema);
            schema2 = null;
            this._serializer2 = context.GetSerializer<System.Collections.Generic.Dictionary<string, string>>(schema2);
            System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>[3];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>(this.PackValueOfName);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>(this.PackValueOfHandle);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>(this.PackValueOfMetadata);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>>(3);
            packOperationTable["Name"] = new System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>(this.PackValueOfName);
            packOperationTable["Handle"] = new System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>(this.PackValueOfHandle);
            packOperationTable["Metadata"] = new System.Action<MsgPack.Packer, Stormancer.Dto.RouteDto>(this.PackValueOfMetadata);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Dto.RouteDto, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Dto.RouteDto, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Dto.RouteDto, bool>>(2);
            nullCheckerTable["Name"] = new System.Func<Stormancer.Dto.RouteDto, bool>(this.IsNameNull);
            nullCheckerTable["Metadata"] = new System.Func<Stormancer.Dto.RouteDto, bool>(this.IsMetadataNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>[3];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>(this.UnpackValueOfName);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>(this.UnpackValueOfHandle);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>(this.UnpackValueOfMetadata);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>>(3);
            unpackOperationTable["Name"] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>(this.UnpackValueOfName);
            unpackOperationTable["Handle"] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>(this.UnpackValueOfHandle);
            unpackOperationTable["Metadata"] = new System.Action<MsgPack.Unpacker, Stormancer.Dto.RouteDto, int, int>(this.UnpackValueOfMetadata);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "Name",
                    "Handle",
                    "Metadata"};
            this.this_SetUnpackedValueOfNameDelegate = new System.Action<Stormancer.Dto.RouteDto, string>(this.SetUnpackedValueOfName);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfHandleDelegate = new System.Action<Stormancer.Dto.RouteDto, ushort>(this.SetUnpackedValueOfHandle);
            this.MsgPack_Serialization_UnpackHelpers_UnpackUInt16ValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, ushort>(MsgPack.Serialization.UnpackHelpers.UnpackUInt16Value);
            this.this_SetUnpackedValueOfMetadataDelegate = new System.Action<Stormancer.Dto.RouteDto, System.Collections.Generic.Dictionary<string, string>>(this.SetUnpackedValueOfMetadata);
        }
        
        private void PackValueOfName(MsgPack.Packer packer, Stormancer.Dto.RouteDto objectTree) {
            this._serializer0.PackTo(packer, objectTree.Name);
        }
        
        private bool IsNameNull(Stormancer.Dto.RouteDto objectTree) {
            return (objectTree.Name == null);
        }
        
        private void PackValueOfHandle(MsgPack.Packer packer, Stormancer.Dto.RouteDto objectTree) {
            this._serializer1.PackTo(packer, objectTree.Handle);
        }
        
        private void PackValueOfMetadata(MsgPack.Packer packer, Stormancer.Dto.RouteDto objectTree) {
            this._serializer2.PackTo(packer, objectTree.Metadata);
        }
        
        private bool IsMetadataNull(Stormancer.Dto.RouteDto objectTree) {
            return (objectTree.Metadata == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Dto.RouteDto objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Dto.RouteDto> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Dto.RouteDto>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Dto.RouteDto> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Dto.RouteDto>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfName(Stormancer.Dto.RouteDto unpackingContext, string unpackedValue) {
            unpackingContext.Name = unpackedValue;
        }
        
        private void UnpackValueOfName(MsgPack.Unpacker unpacker, Stormancer.Dto.RouteDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Dto.RouteDto, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Dto.RouteDto, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "Name";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfNameDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfHandle(Stormancer.Dto.RouteDto unpackingContext, ushort unpackedValue) {
            unpackingContext.Handle = unpackedValue;
        }
        
        private void UnpackValueOfHandle(MsgPack.Unpacker unpacker, Stormancer.Dto.RouteDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Dto.RouteDto, ushort> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Dto.RouteDto, ushort>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(ushort);
            unpackHelperParameters0.MemberName = "Handle";
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackUInt16ValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfHandleDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfMetadata(Stormancer.Dto.RouteDto unpackingContext, System.Collections.Generic.Dictionary<string, string> unpackedValue) {
            unpackingContext.Metadata = unpackedValue;
        }
        
        private void UnpackValueOfMetadata(MsgPack.Unpacker unpacker, Stormancer.Dto.RouteDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Dto.RouteDto, System.Collections.Generic.Dictionary<string, string>> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Dto.RouteDto, System.Collections.Generic.Dictionary<string, string>>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer2;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(System.Collections.Generic.Dictionary<string, string>);
            unpackHelperParameters1.MemberName = "Metadata";
            unpackHelperParameters1.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters1.DirectRead = null;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfMetadataDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters1);
        }
        
        protected internal override Stormancer.Dto.RouteDto UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Dto.RouteDto result = default(Stormancer.Dto.RouteDto);
            result = new Stormancer.Dto.RouteDto();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Dto.RouteDto>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Dto.RouteDto>(), this._unpackOperationTable);
            }
        }
    }
}

