//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_P2PSessionSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.P2PSession> {
        
        private MsgPack.Serialization.MessagePackSerializer<byte[]> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<ulong> _serializer1;
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer2;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.P2PSession>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.P2PSession>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.P2PSession, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.P2PSession, byte[]> this_SetUnpackedValueOfSessionIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, byte[]> MsgPack_Serialization_UnpackHelpers_UnpackBinaryValueDelegate;
        
        private System.Action<Stormancer.P2PSession, ulong> this_SetUnpackedValueOfRemotePeerDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, ulong> MsgPack_Serialization_UnpackHelpers_UnpackUInt64ValueDelegate;
        
        private System.Action<Stormancer.P2PSession, string> this_SetUnpackedValueOfSceneIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>> _unpackOperationTable;
        
        public Stormancer_P2PSessionSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<byte[]>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<ulong>(schema1);
            MsgPack.Serialization.PolymorphismSchema schema2 = default(MsgPack.Serialization.PolymorphismSchema);
            schema2 = null;
            this._serializer2 = context.GetSerializer<string>(schema2);
            System.Action<MsgPack.Packer, Stormancer.P2PSession>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.P2PSession>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.P2PSession>[3];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.P2PSession>(this.PackValueOfSessionId);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.P2PSession>(this.PackValueOfRemotePeer);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.P2PSession>(this.PackValueOfSceneId);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.P2PSession>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.P2PSession>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.P2PSession>>(3);
            packOperationTable["SessionId"] = new System.Action<MsgPack.Packer, Stormancer.P2PSession>(this.PackValueOfSessionId);
            packOperationTable["RemotePeer"] = new System.Action<MsgPack.Packer, Stormancer.P2PSession>(this.PackValueOfRemotePeer);
            packOperationTable["SceneId"] = new System.Action<MsgPack.Packer, Stormancer.P2PSession>(this.PackValueOfSceneId);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.P2PSession, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.P2PSession, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.P2PSession, bool>>(2);
            nullCheckerTable["SessionId"] = new System.Func<Stormancer.P2PSession, bool>(this.IsSessionIdNull);
            nullCheckerTable["SceneId"] = new System.Func<Stormancer.P2PSession, bool>(this.IsSceneIdNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>[3];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>(this.UnpackValueOfSessionId);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>(this.UnpackValueOfRemotePeer);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>(this.UnpackValueOfSceneId);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>>(3);
            unpackOperationTable["SessionId"] = new System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>(this.UnpackValueOfSessionId);
            unpackOperationTable["RemotePeer"] = new System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>(this.UnpackValueOfRemotePeer);
            unpackOperationTable["SceneId"] = new System.Action<MsgPack.Unpacker, Stormancer.P2PSession, int, int>(this.UnpackValueOfSceneId);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "SessionId",
                    "RemotePeer",
                    "SceneId"};
            this.this_SetUnpackedValueOfSessionIdDelegate = new System.Action<Stormancer.P2PSession, byte[]>(this.SetUnpackedValueOfSessionId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackBinaryValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, byte[]>(MsgPack.Serialization.UnpackHelpers.UnpackBinaryValue);
            this.this_SetUnpackedValueOfRemotePeerDelegate = new System.Action<Stormancer.P2PSession, ulong>(this.SetUnpackedValueOfRemotePeer);
            this.MsgPack_Serialization_UnpackHelpers_UnpackUInt64ValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, ulong>(MsgPack.Serialization.UnpackHelpers.UnpackUInt64Value);
            this.this_SetUnpackedValueOfSceneIdDelegate = new System.Action<Stormancer.P2PSession, string>(this.SetUnpackedValueOfSceneId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
        }
        
        private void PackValueOfSessionId(MsgPack.Packer packer, Stormancer.P2PSession objectTree) {
            this._serializer0.PackTo(packer, objectTree.SessionId);
        }
        
        private bool IsSessionIdNull(Stormancer.P2PSession objectTree) {
            return (objectTree.SessionId == null);
        }
        
        private void PackValueOfRemotePeer(MsgPack.Packer packer, Stormancer.P2PSession objectTree) {
            this._serializer1.PackTo(packer, objectTree.RemotePeer);
        }
        
        private void PackValueOfSceneId(MsgPack.Packer packer, Stormancer.P2PSession objectTree) {
            this._serializer2.PackTo(packer, objectTree.SceneId);
        }
        
        private bool IsSceneIdNull(Stormancer.P2PSession objectTree) {
            return (objectTree.SceneId == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.P2PSession objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.P2PSession> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.P2PSession>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.P2PSession> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.P2PSession>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfSessionId(Stormancer.P2PSession unpackingContext, byte[] unpackedValue) {
            unpackingContext.SessionId = unpackedValue;
        }
        
        private void UnpackValueOfSessionId(MsgPack.Unpacker unpacker, Stormancer.P2PSession unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.P2PSession, byte[]> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.P2PSession, byte[]>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(byte[]);
            unpackHelperParameters.MemberName = "SessionId";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackBinaryValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfSessionIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfRemotePeer(Stormancer.P2PSession unpackingContext, ulong unpackedValue) {
            unpackingContext.RemotePeer = unpackedValue;
        }
        
        private void UnpackValueOfRemotePeer(MsgPack.Unpacker unpacker, Stormancer.P2PSession unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.P2PSession, ulong> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.P2PSession, ulong>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(ulong);
            unpackHelperParameters0.MemberName = "RemotePeer";
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackUInt64ValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfRemotePeerDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfSceneId(Stormancer.P2PSession unpackingContext, string unpackedValue) {
            unpackingContext.SceneId = unpackedValue;
        }
        
        private void UnpackValueOfSceneId(MsgPack.Unpacker unpacker, Stormancer.P2PSession unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.P2PSession, string> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.P2PSession, string>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer2;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(string);
            unpackHelperParameters1.MemberName = "SceneId";
            unpackHelperParameters1.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters1.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfSceneIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters1);
        }
        
        protected internal override Stormancer.P2PSession UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.P2PSession result = default(Stormancer.P2PSession);
            result = new Stormancer.P2PSession();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.P2PSession>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.P2PSession>(), this._unpackOperationTable);
            }
        }
    }
}

