//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_AuthParametersSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.AuthParameters> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<System.Collections.Generic.Dictionary<string, string>> _serializer1;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.AuthParameters, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.AuthParameters, string> this_SetUnpackedValueOfTypeDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.AuthParameters, System.Collections.Generic.Dictionary<string, string>> this_SetUnpackedValueOfParametersDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_AuthParametersSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<System.Collections.Generic.Dictionary<string, string>>(schema1);
            System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>[2];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>(this.PackValueOfType);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>(this.PackValueOfParameters);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>>(2);
            packOperationTable["Type"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>(this.PackValueOfType);
            packOperationTable["Parameters"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.AuthParameters>(this.PackValueOfParameters);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.AuthParameters, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.AuthParameters, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.AuthParameters, bool>>(2);
            nullCheckerTable["Type"] = new System.Func<Stormancer.Plugins.AuthParameters, bool>(this.IsTypeNull);
            nullCheckerTable["Parameters"] = new System.Func<Stormancer.Plugins.AuthParameters, bool>(this.IsParametersNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>[2];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>(this.UnpackValueOfType);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>(this.UnpackValueOfParameters);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>>(2);
            unpackOperationTable["Type"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>(this.UnpackValueOfType);
            unpackOperationTable["Parameters"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.AuthParameters, int, int>(this.UnpackValueOfParameters);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "Type",
                    "Parameters"};
            this.this_SetUnpackedValueOfTypeDelegate = new System.Action<Stormancer.Plugins.AuthParameters, string>(this.SetUnpackedValueOfType);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfParametersDelegate = new System.Action<Stormancer.Plugins.AuthParameters, System.Collections.Generic.Dictionary<string, string>>(this.SetUnpackedValueOfParameters);
        }
        
        private void PackValueOfType(MsgPack.Packer packer, Stormancer.Plugins.AuthParameters objectTree) {
            this._serializer0.PackTo(packer, objectTree.Type);
        }
        
        private bool IsTypeNull(Stormancer.Plugins.AuthParameters objectTree) {
            return (objectTree.Type == null);
        }
        
        private void PackValueOfParameters(MsgPack.Packer packer, Stormancer.Plugins.AuthParameters objectTree) {
            this._serializer1.PackTo(packer, objectTree.Parameters);
        }
        
        private bool IsParametersNull(Stormancer.Plugins.AuthParameters objectTree) {
            return (objectTree.Parameters == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.AuthParameters objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.AuthParameters> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.AuthParameters>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.AuthParameters> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.AuthParameters>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfType(Stormancer.Plugins.AuthParameters unpackingContext, string unpackedValue) {
            unpackingContext.Type = unpackedValue;
        }
        
        private void UnpackValueOfType(MsgPack.Unpacker unpacker, Stormancer.Plugins.AuthParameters unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.AuthParameters, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.AuthParameters, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "Type";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfTypeDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfParameters(Stormancer.Plugins.AuthParameters unpackingContext, System.Collections.Generic.Dictionary<string, string> unpackedValue) {
            unpackingContext.Parameters = unpackedValue;
        }
        
        private void UnpackValueOfParameters(MsgPack.Unpacker unpacker, Stormancer.Plugins.AuthParameters unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.AuthParameters, System.Collections.Generic.Dictionary<string, string>> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.AuthParameters, System.Collections.Generic.Dictionary<string, string>>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(System.Collections.Generic.Dictionary<string, string>);
            unpackHelperParameters0.MemberName = "Parameters";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = null;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfParametersDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        protected internal override Stormancer.Plugins.AuthParameters UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.AuthParameters result = default(Stormancer.Plugins.AuthParameters);
            result = new Stormancer.Plugins.AuthParameters();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.AuthParameters>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.AuthParameters>(), this._unpackOperationTable);
            }
        }
    }
}

