//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_SetResultSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.SetResult> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<int> _serializer1;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.SetResult, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.SetResult, string> this_SetUnpackedValueOfWinnerIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.SetResult, int> this_SetUnpackedValueOfWinnerScoreDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, int> MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate;
        
        private System.Action<Stormancer.Plugins.SetResult, int> this_SetUnpackedValueOfLoserScoreDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_SetResultSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<int>(schema1);
            System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>[3];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>(this.PackValueOfWinnerId);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>(this.PackValueOfWinnerScore);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>(this.PackValueOfLoserScore);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>>(3);
            packOperationTable["WinnerId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>(this.PackValueOfWinnerId);
            packOperationTable["WinnerScore"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>(this.PackValueOfWinnerScore);
            packOperationTable["LoserScore"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.SetResult>(this.PackValueOfLoserScore);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.SetResult, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.SetResult, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.SetResult, bool>>(1);
            nullCheckerTable["WinnerId"] = new System.Func<Stormancer.Plugins.SetResult, bool>(this.IsWinnerIdNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>[3];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>(this.UnpackValueOfWinnerId);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>(this.UnpackValueOfWinnerScore);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>(this.UnpackValueOfLoserScore);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>>(3);
            unpackOperationTable["WinnerId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>(this.UnpackValueOfWinnerId);
            unpackOperationTable["WinnerScore"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>(this.UnpackValueOfWinnerScore);
            unpackOperationTable["LoserScore"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.SetResult, int, int>(this.UnpackValueOfLoserScore);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "WinnerId",
                    "WinnerScore",
                    "LoserScore"};
            this.this_SetUnpackedValueOfWinnerIdDelegate = new System.Action<Stormancer.Plugins.SetResult, string>(this.SetUnpackedValueOfWinnerId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfWinnerScoreDelegate = new System.Action<Stormancer.Plugins.SetResult, int>(this.SetUnpackedValueOfWinnerScore);
            this.MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, int>(MsgPack.Serialization.UnpackHelpers.UnpackInt32Value);
            this.this_SetUnpackedValueOfLoserScoreDelegate = new System.Action<Stormancer.Plugins.SetResult, int>(this.SetUnpackedValueOfLoserScore);
        }
        
        private void PackValueOfWinnerId(MsgPack.Packer packer, Stormancer.Plugins.SetResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.WinnerId);
        }
        
        private bool IsWinnerIdNull(Stormancer.Plugins.SetResult objectTree) {
            return (objectTree.WinnerId == null);
        }
        
        private void PackValueOfWinnerScore(MsgPack.Packer packer, Stormancer.Plugins.SetResult objectTree) {
            this._serializer1.PackTo(packer, objectTree.WinnerScore);
        }
        
        private void PackValueOfLoserScore(MsgPack.Packer packer, Stormancer.Plugins.SetResult objectTree) {
            this._serializer1.PackTo(packer, objectTree.LoserScore);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.SetResult objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.SetResult> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.SetResult>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.SetResult> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.SetResult>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfWinnerId(Stormancer.Plugins.SetResult unpackingContext, string unpackedValue) {
            unpackingContext.WinnerId = unpackedValue;
        }
        
        private void UnpackValueOfWinnerId(MsgPack.Unpacker unpacker, Stormancer.Plugins.SetResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.SetResult, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.SetResult, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "WinnerId";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfWinnerIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfWinnerScore(Stormancer.Plugins.SetResult unpackingContext, int unpackedValue) {
            unpackingContext.WinnerScore = unpackedValue;
        }
        
        private void UnpackValueOfWinnerScore(MsgPack.Unpacker unpacker, Stormancer.Plugins.SetResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.SetResult, int> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.SetResult, int>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(int);
            unpackHelperParameters0.MemberName = "WinnerScore";
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfWinnerScoreDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfLoserScore(Stormancer.Plugins.SetResult unpackingContext, int unpackedValue) {
            unpackingContext.LoserScore = unpackedValue;
        }
        
        private void UnpackValueOfLoserScore(MsgPack.Unpacker unpacker, Stormancer.Plugins.SetResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.SetResult, int> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.SetResult, int>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer1;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(int);
            unpackHelperParameters1.MemberName = "LoserScore";
            unpackHelperParameters1.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfLoserScoreDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters1);
        }
        
        protected internal override Stormancer.Plugins.SetResult UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.SetResult result = default(Stormancer.Plugins.SetResult);
            result = new Stormancer.Plugins.SetResult();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.SetResult>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.SetResult>(), this._unpackOperationTable);
            }
        }
    }
}

