//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_LeaderboardResultSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.LeaderboardResult> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking>> _serializer1;
        
        private MsgPack.Serialization.MessagePackSerializer<long> _serializer2;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.LeaderboardResult, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.LeaderboardResult, string> this_SetUnpackedValueOfLeaderboardNameDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.LeaderboardResult, System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking>> this_SetUnpackedValueOfResultsDelegate;
        
        private System.Action<Stormancer.Plugins.LeaderboardResult, string> this_SetUnpackedValueOfNextDelegate;
        
        private System.Action<Stormancer.Plugins.LeaderboardResult, string> this_SetUnpackedValueOfPreviousDelegate;
        
        private System.Action<Stormancer.Plugins.LeaderboardResult, long> this_SetUnpackedValueOfTotalDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, long> MsgPack_Serialization_UnpackHelpers_UnpackInt64ValueDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_LeaderboardResultSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking>>(schema1);
            MsgPack.Serialization.PolymorphismSchema schema2 = default(MsgPack.Serialization.PolymorphismSchema);
            schema2 = null;
            this._serializer2 = context.GetSerializer<long>(schema2);
            System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>[5];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfLeaderboardName);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfResults);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfNext);
            packOperationList[3] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfPrevious);
            packOperationList[4] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfTotal);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>>(5);
            packOperationTable["LeaderboardName"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfLeaderboardName);
            packOperationTable["Results"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfResults);
            packOperationTable["Next"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfNext);
            packOperationTable["Previous"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfPrevious);
            packOperationTable["Total"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.LeaderboardResult>(this.PackValueOfTotal);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.LeaderboardResult, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.LeaderboardResult, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.LeaderboardResult, bool>>(4);
            nullCheckerTable["LeaderboardName"] = new System.Func<Stormancer.Plugins.LeaderboardResult, bool>(this.IsLeaderboardNameNull);
            nullCheckerTable["Results"] = new System.Func<Stormancer.Plugins.LeaderboardResult, bool>(this.IsResultsNull);
            nullCheckerTable["Next"] = new System.Func<Stormancer.Plugins.LeaderboardResult, bool>(this.IsNextNull);
            nullCheckerTable["Previous"] = new System.Func<Stormancer.Plugins.LeaderboardResult, bool>(this.IsPreviousNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>[5];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfLeaderboardName);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfResults);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfNext);
            unpackOperationList[3] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfPrevious);
            unpackOperationList[4] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfTotal);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>>(5);
            unpackOperationTable["LeaderboardName"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfLeaderboardName);
            unpackOperationTable["Results"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfResults);
            unpackOperationTable["Next"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfNext);
            unpackOperationTable["Previous"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfPrevious);
            unpackOperationTable["Total"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.LeaderboardResult, int, int>(this.UnpackValueOfTotal);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "LeaderboardName",
                    "Results",
                    "Next",
                    "Previous",
                    "Total"};
            this.this_SetUnpackedValueOfLeaderboardNameDelegate = new System.Action<Stormancer.Plugins.LeaderboardResult, string>(this.SetUnpackedValueOfLeaderboardName);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfResultsDelegate = new System.Action<Stormancer.Plugins.LeaderboardResult, System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking>>(this.SetUnpackedValueOfResults);
            this.this_SetUnpackedValueOfNextDelegate = new System.Action<Stormancer.Plugins.LeaderboardResult, string>(this.SetUnpackedValueOfNext);
            this.this_SetUnpackedValueOfPreviousDelegate = new System.Action<Stormancer.Plugins.LeaderboardResult, string>(this.SetUnpackedValueOfPrevious);
            this.this_SetUnpackedValueOfTotalDelegate = new System.Action<Stormancer.Plugins.LeaderboardResult, long>(this.SetUnpackedValueOfTotal);
            this.MsgPack_Serialization_UnpackHelpers_UnpackInt64ValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, long>(MsgPack.Serialization.UnpackHelpers.UnpackInt64Value);
        }
        
        private void PackValueOfLeaderboardName(MsgPack.Packer packer, Stormancer.Plugins.LeaderboardResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.LeaderboardName);
        }
        
        private bool IsLeaderboardNameNull(Stormancer.Plugins.LeaderboardResult objectTree) {
            return (objectTree.LeaderboardName == null);
        }
        
        private void PackValueOfResults(MsgPack.Packer packer, Stormancer.Plugins.LeaderboardResult objectTree) {
            this._serializer1.PackTo(packer, objectTree.Results);
        }
        
        private bool IsResultsNull(Stormancer.Plugins.LeaderboardResult objectTree) {
            return (objectTree.Results == null);
        }
        
        private void PackValueOfNext(MsgPack.Packer packer, Stormancer.Plugins.LeaderboardResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.Next);
        }
        
        private bool IsNextNull(Stormancer.Plugins.LeaderboardResult objectTree) {
            return (objectTree.Next == null);
        }
        
        private void PackValueOfPrevious(MsgPack.Packer packer, Stormancer.Plugins.LeaderboardResult objectTree) {
            this._serializer0.PackTo(packer, objectTree.Previous);
        }
        
        private bool IsPreviousNull(Stormancer.Plugins.LeaderboardResult objectTree) {
            return (objectTree.Previous == null);
        }
        
        private void PackValueOfTotal(MsgPack.Packer packer, Stormancer.Plugins.LeaderboardResult objectTree) {
            this._serializer2.PackTo(packer, objectTree.Total);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.LeaderboardResult objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.LeaderboardResult> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.LeaderboardResult>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.LeaderboardResult> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.LeaderboardResult>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfLeaderboardName(Stormancer.Plugins.LeaderboardResult unpackingContext, string unpackedValue) {
            unpackingContext.LeaderboardName = unpackedValue;
        }
        
        private void UnpackValueOfLeaderboardName(MsgPack.Unpacker unpacker, Stormancer.Plugins.LeaderboardResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "LeaderboardName";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfLeaderboardNameDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfResults(Stormancer.Plugins.LeaderboardResult unpackingContext, System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking> unpackedValue) {
            unpackingContext.Results = unpackedValue;
        }
        
        private void UnpackValueOfResults(MsgPack.Unpacker unpacker, Stormancer.Plugins.LeaderboardResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking>> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking>>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(System.Collections.Generic.List<Stormancer.Plugins.LeaderboardRanking>);
            unpackHelperParameters0.MemberName = "Results";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = null;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfResultsDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfNext(Stormancer.Plugins.LeaderboardResult unpackingContext, string unpackedValue) {
            unpackingContext.Next = unpackedValue;
        }
        
        private void UnpackValueOfNext(MsgPack.Unpacker unpacker, Stormancer.Plugins.LeaderboardResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, string> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, string>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer0;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(string);
            unpackHelperParameters1.MemberName = "Next";
            unpackHelperParameters1.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters1.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfNextDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters1);
        }
        
        private void SetUnpackedValueOfPrevious(Stormancer.Plugins.LeaderboardResult unpackingContext, string unpackedValue) {
            unpackingContext.Previous = unpackedValue;
        }
        
        private void UnpackValueOfPrevious(MsgPack.Unpacker unpacker, Stormancer.Plugins.LeaderboardResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, string> unpackHelperParameters2 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.LeaderboardResult, string>);
            unpackHelperParameters2.Unpacker = unpacker;
            unpackHelperParameters2.UnpackingContext = unpackingContext;
            unpackHelperParameters2.Serializer = this._serializer0;
            unpackHelperParameters2.ItemsCount = itemsCount;
            unpackHelperParameters2.Unpacked = indexOfItem;
            unpackHelperParameters2.TargetObjectType = typeof(string);
            unpackHelperParameters2.MemberName = "Previous";
            unpackHelperParameters2.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters2.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters2.Setter = this.this_SetUnpackedValueOfPreviousDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters2);
        }
        
        private void SetUnpackedValueOfTotal(Stormancer.Plugins.LeaderboardResult unpackingContext, long unpackedValue) {
            unpackingContext.Total = unpackedValue;
        }
        
        private void UnpackValueOfTotal(MsgPack.Unpacker unpacker, Stormancer.Plugins.LeaderboardResult unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.LeaderboardResult, long> unpackHelperParameters3 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.LeaderboardResult, long>);
            unpackHelperParameters3.Unpacker = unpacker;
            unpackHelperParameters3.UnpackingContext = unpackingContext;
            unpackHelperParameters3.Serializer = this._serializer2;
            unpackHelperParameters3.ItemsCount = itemsCount;
            unpackHelperParameters3.Unpacked = indexOfItem;
            unpackHelperParameters3.TargetObjectType = typeof(long);
            unpackHelperParameters3.MemberName = "Total";
            unpackHelperParameters3.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackInt64ValueDelegate;
            unpackHelperParameters3.Setter = this.this_SetUnpackedValueOfTotalDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters3);
        }
        
        protected internal override Stormancer.Plugins.LeaderboardResult UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.LeaderboardResult result = default(Stormancer.Plugins.LeaderboardResult);
            result = new Stormancer.Plugins.LeaderboardResult();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.LeaderboardResult>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.LeaderboardResult>(), this._unpackOperationTable);
            }
        }
    }
}

