//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_GameFinderResponseDTOSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.GameFinderResponseDTO> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<System.Collections.Generic.Dictionary<string, string>> _serializer1;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.GameFinderResponseDTO, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.GameFinderResponseDTO, string> this_SetUnpackedValueOfGameTokenDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.GameFinderResponseDTO, System.Collections.Generic.Dictionary<string, string>> this_SetUnpackedValueOfOptionalParametersDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_GameFinderResponseDTOSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<System.Collections.Generic.Dictionary<string, string>>(schema1);
            System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>[2];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>(this.PackValueOfGameToken);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>(this.PackValueOfOptionalParameters);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>>(2);
            packOperationTable["GameToken"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>(this.PackValueOfGameToken);
            packOperationTable["OptionalParameters"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.GameFinderResponseDTO>(this.PackValueOfOptionalParameters);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameFinderResponseDTO, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameFinderResponseDTO, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.GameFinderResponseDTO, bool>>(2);
            nullCheckerTable["GameToken"] = new System.Func<Stormancer.Plugins.GameFinderResponseDTO, bool>(this.IsGameTokenNull);
            nullCheckerTable["OptionalParameters"] = new System.Func<Stormancer.Plugins.GameFinderResponseDTO, bool>(this.IsOptionalParametersNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>[2];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>(this.UnpackValueOfGameToken);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>(this.UnpackValueOfOptionalParameters);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>>(2);
            unpackOperationTable["GameToken"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>(this.UnpackValueOfGameToken);
            unpackOperationTable["OptionalParameters"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.GameFinderResponseDTO, int, int>(this.UnpackValueOfOptionalParameters);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "GameToken",
                    "OptionalParameters"};
            this.this_SetUnpackedValueOfGameTokenDelegate = new System.Action<Stormancer.Plugins.GameFinderResponseDTO, string>(this.SetUnpackedValueOfGameToken);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfOptionalParametersDelegate = new System.Action<Stormancer.Plugins.GameFinderResponseDTO, System.Collections.Generic.Dictionary<string, string>>(this.SetUnpackedValueOfOptionalParameters);
        }
        
        private void PackValueOfGameToken(MsgPack.Packer packer, Stormancer.Plugins.GameFinderResponseDTO objectTree) {
            this._serializer0.PackTo(packer, objectTree.GameToken);
        }
        
        private bool IsGameTokenNull(Stormancer.Plugins.GameFinderResponseDTO objectTree) {
            return (objectTree.GameToken == null);
        }
        
        private void PackValueOfOptionalParameters(MsgPack.Packer packer, Stormancer.Plugins.GameFinderResponseDTO objectTree) {
            this._serializer1.PackTo(packer, objectTree.OptionalParameters);
        }
        
        private bool IsOptionalParametersNull(Stormancer.Plugins.GameFinderResponseDTO objectTree) {
            return (objectTree.OptionalParameters == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.GameFinderResponseDTO objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.GameFinderResponseDTO> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.GameFinderResponseDTO>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.GameFinderResponseDTO> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.GameFinderResponseDTO>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfGameToken(Stormancer.Plugins.GameFinderResponseDTO unpackingContext, string unpackedValue) {
            unpackingContext.GameToken = unpackedValue;
        }
        
        private void UnpackValueOfGameToken(MsgPack.Unpacker unpacker, Stormancer.Plugins.GameFinderResponseDTO unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameFinderResponseDTO, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameFinderResponseDTO, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "GameToken";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfGameTokenDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfOptionalParameters(Stormancer.Plugins.GameFinderResponseDTO unpackingContext, System.Collections.Generic.Dictionary<string, string> unpackedValue) {
            unpackingContext.OptionalParameters = unpackedValue;
        }
        
        private void UnpackValueOfOptionalParameters(MsgPack.Unpacker unpacker, Stormancer.Plugins.GameFinderResponseDTO unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameFinderResponseDTO, System.Collections.Generic.Dictionary<string, string>> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.GameFinderResponseDTO, System.Collections.Generic.Dictionary<string, string>>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(System.Collections.Generic.Dictionary<string, string>);
            unpackHelperParameters0.MemberName = "OptionalParameters";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = null;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfOptionalParametersDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        protected internal override Stormancer.Plugins.GameFinderResponseDTO UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.GameFinderResponseDTO result = default(Stormancer.Plugins.GameFinderResponseDTO);
            result = new Stormancer.Plugins.GameFinderResponseDTO();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.GameFinderResponseDTO>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.GameFinderResponseDTO>(), this._unpackOperationTable);
            }
        }
    }
}

