//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_ServerStartedMessageSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.ServerStartedMessage> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.ServerStartedMessage, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.ServerStartedMessage, string> this_SetUnpackedValueOfP2PTokenDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_ServerStartedMessageSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>[1];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>(this.PackValueOfP2PToken);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>>(1);
            packOperationTable["P2PToken"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ServerStartedMessage>(this.PackValueOfP2PToken);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.ServerStartedMessage, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.ServerStartedMessage, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.ServerStartedMessage, bool>>(1);
            nullCheckerTable["P2PToken"] = new System.Func<Stormancer.Plugins.ServerStartedMessage, bool>(this.IsP2PTokenNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>[1];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>(this.UnpackValueOfP2PToken);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>>(1);
            unpackOperationTable["P2PToken"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ServerStartedMessage, int, int>(this.UnpackValueOfP2PToken);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "P2PToken"};
            this.this_SetUnpackedValueOfP2PTokenDelegate = new System.Action<Stormancer.Plugins.ServerStartedMessage, string>(this.SetUnpackedValueOfP2PToken);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
        }
        
        private void PackValueOfP2PToken(MsgPack.Packer packer, Stormancer.Plugins.ServerStartedMessage objectTree) {
            this._serializer0.PackTo(packer, objectTree.P2PToken);
        }
        
        private bool IsP2PTokenNull(Stormancer.Plugins.ServerStartedMessage objectTree) {
            return (objectTree.P2PToken == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.ServerStartedMessage objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.ServerStartedMessage> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.ServerStartedMessage>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.ServerStartedMessage> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.ServerStartedMessage>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfP2PToken(Stormancer.Plugins.ServerStartedMessage unpackingContext, string unpackedValue) {
            unpackingContext.P2PToken = unpackedValue;
        }
        
        private void UnpackValueOfP2PToken(MsgPack.Unpacker unpacker, Stormancer.Plugins.ServerStartedMessage unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.ServerStartedMessage, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.ServerStartedMessage, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "P2PToken";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfP2PTokenDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        protected internal override Stormancer.Plugins.ServerStartedMessage UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.ServerStartedMessage result = default(Stormancer.Plugins.ServerStartedMessage);
            result = new Stormancer.Plugins.ServerStartedMessage();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.ServerStartedMessage>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.ServerStartedMessage>(), this._unpackOperationTable);
            }
        }
    }
}

