//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_FriendSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.Friend> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<System.DateTime> _serializer1;
        
        private MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.FriendStatus> _serializer2;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.Friend, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.Friend, string> this_SetUnpackedValueOfUserIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.Friend, string> this_SetUnpackedValueOfDetailsDelegate;
        
        private System.Action<Stormancer.Plugins.Friend, System.DateTime> this_SetUnpackedValueOfLastConnectedDelegate;
        
        private System.Action<Stormancer.Plugins.Friend, Stormancer.Plugins.FriendStatus> this_SetUnpackedValueOfStatusDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_FriendSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            this._serializer1 = context.GetSerializer<System.DateTime>(MsgPack.Serialization.DateTimeMessagePackSerializerHelpers.DetermineDateTimeConversionMethod(context, MsgPack.Serialization.DateTimeMemberConversionMethod.Default));
            this._serializer2 = context.GetSerializer<Stormancer.Plugins.FriendStatus>(MsgPack.Serialization.EnumMessagePackSerializerHelpers.DetermineEnumSerializationMethod(context, typeof(Stormancer.Plugins.FriendStatus), MsgPack.Serialization.EnumMemberSerializationMethod.Default));
            System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>[4];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfUserId);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfDetails);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfLastConnected);
            packOperationList[3] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfStatus);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>>(4);
            packOperationTable["UserId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfUserId);
            packOperationTable["Details"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfDetails);
            packOperationTable["LastConnected"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfLastConnected);
            packOperationTable["Status"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.Friend>(this.PackValueOfStatus);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.Friend, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.Friend, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.Friend, bool>>(2);
            nullCheckerTable["UserId"] = new System.Func<Stormancer.Plugins.Friend, bool>(this.IsUserIdNull);
            nullCheckerTable["Details"] = new System.Func<Stormancer.Plugins.Friend, bool>(this.IsDetailsNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>[4];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfUserId);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfDetails);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfLastConnected);
            unpackOperationList[3] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfStatus);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>>(4);
            unpackOperationTable["UserId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfUserId);
            unpackOperationTable["Details"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfDetails);
            unpackOperationTable["LastConnected"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfLastConnected);
            unpackOperationTable["Status"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.Friend, int, int>(this.UnpackValueOfStatus);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "UserId",
                    "Details",
                    "LastConnected",
                    "Status"};
            this.this_SetUnpackedValueOfUserIdDelegate = new System.Action<Stormancer.Plugins.Friend, string>(this.SetUnpackedValueOfUserId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfDetailsDelegate = new System.Action<Stormancer.Plugins.Friend, string>(this.SetUnpackedValueOfDetails);
            this.this_SetUnpackedValueOfLastConnectedDelegate = new System.Action<Stormancer.Plugins.Friend, System.DateTime>(this.SetUnpackedValueOfLastConnected);
            this.this_SetUnpackedValueOfStatusDelegate = new System.Action<Stormancer.Plugins.Friend, Stormancer.Plugins.FriendStatus>(this.SetUnpackedValueOfStatus);
        }
        
        private void PackValueOfUserId(MsgPack.Packer packer, Stormancer.Plugins.Friend objectTree) {
            this._serializer0.PackTo(packer, objectTree.UserId);
        }
        
        private bool IsUserIdNull(Stormancer.Plugins.Friend objectTree) {
            return (objectTree.UserId == null);
        }
        
        private void PackValueOfDetails(MsgPack.Packer packer, Stormancer.Plugins.Friend objectTree) {
            this._serializer0.PackTo(packer, objectTree.Details);
        }
        
        private bool IsDetailsNull(Stormancer.Plugins.Friend objectTree) {
            return (objectTree.Details == null);
        }
        
        private void PackValueOfLastConnected(MsgPack.Packer packer, Stormancer.Plugins.Friend objectTree) {
            this._serializer1.PackTo(packer, objectTree.LastConnected);
        }
        
        private void PackValueOfStatus(MsgPack.Packer packer, Stormancer.Plugins.Friend objectTree) {
            this._serializer2.PackTo(packer, objectTree.Status);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.Friend objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.Friend> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.Friend>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.Friend> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.Friend>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfUserId(Stormancer.Plugins.Friend unpackingContext, string unpackedValue) {
            unpackingContext.UserId = unpackedValue;
        }
        
        private void UnpackValueOfUserId(MsgPack.Unpacker unpacker, Stormancer.Plugins.Friend unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Friend, string> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Friend, string>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(string);
            unpackHelperParameters.MemberName = "UserId";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfUserIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfDetails(Stormancer.Plugins.Friend unpackingContext, string unpackedValue) {
            unpackingContext.Details = unpackedValue;
        }
        
        private void UnpackValueOfDetails(MsgPack.Unpacker unpacker, Stormancer.Plugins.Friend unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Friend, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.Friend, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer0;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "Details";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfDetailsDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfLastConnected(Stormancer.Plugins.Friend unpackingContext, System.DateTime unpackedValue) {
            unpackingContext.LastConnected = unpackedValue;
        }
        
        private void UnpackValueOfLastConnected(MsgPack.Unpacker unpacker, Stormancer.Plugins.Friend unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.Friend, System.DateTime> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.Friend, System.DateTime>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer1;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(System.DateTime);
            unpackHelperParameters1.MemberName = "LastConnected";
            unpackHelperParameters1.DirectRead = null;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfLastConnectedDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters1);
        }
        
        private void SetUnpackedValueOfStatus(Stormancer.Plugins.Friend unpackingContext, Stormancer.Plugins.FriendStatus unpackedValue) {
            unpackingContext.Status = unpackedValue;
        }
        
        private void UnpackValueOfStatus(MsgPack.Unpacker unpacker, Stormancer.Plugins.Friend unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.Friend, Stormancer.Plugins.FriendStatus> unpackHelperParameters2 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.Friend, Stormancer.Plugins.FriendStatus>);
            unpackHelperParameters2.Unpacker = unpacker;
            unpackHelperParameters2.UnpackingContext = unpackingContext;
            unpackHelperParameters2.Serializer = this._serializer2;
            unpackHelperParameters2.ItemsCount = itemsCount;
            unpackHelperParameters2.Unpacked = indexOfItem;
            unpackHelperParameters2.TargetObjectType = typeof(Stormancer.Plugins.FriendStatus);
            unpackHelperParameters2.MemberName = "Status";
            unpackHelperParameters2.DirectRead = null;
            unpackHelperParameters2.Setter = this.this_SetUnpackedValueOfStatusDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters2);
        }
        
        protected internal override Stormancer.Plugins.Friend UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.Friend result = default(Stormancer.Plugins.Friend);
            result = new Stormancer.Plugins.Friend();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.Friend>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.Friend>(), this._unpackOperationTable);
            }
        }
    }
}

