//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_ReadyVerificationRequestDtoSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.ReadyVerificationRequestDto> {
        
        private MsgPack.Serialization.MessagePackSerializer<System.Collections.Generic.Dictionary<string, int>> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer1;
        
        private MsgPack.Serialization.MessagePackSerializer<int> _serializer2;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.ReadyVerificationRequestDto, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, System.Collections.Generic.Dictionary<string, int>> this_SetUnpackedValueOfMembersDelegate;
        
        private System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, string> this_SetUnpackedValueOfMatchIdDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, int> this_SetUnpackedValueOfTimeoutDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, int> MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate;
        
        private System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, int> this_SetUnpackedValueOfMembersCountReadyDelegate;
        
        private System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, int> this_SetUnpackedValueOfMembersCountTotalDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_ReadyVerificationRequestDtoSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<System.Collections.Generic.Dictionary<string, int>>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<string>(schema1);
            MsgPack.Serialization.PolymorphismSchema schema2 = default(MsgPack.Serialization.PolymorphismSchema);
            schema2 = null;
            this._serializer2 = context.GetSerializer<int>(schema2);
            System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>[5];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMembers);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMatchId);
            packOperationList[2] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfTimeout);
            packOperationList[3] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMembersCountReady);
            packOperationList[4] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMembersCountTotal);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>>(5);
            packOperationTable["Members"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMembers);
            packOperationTable["MatchId"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMatchId);
            packOperationTable["Timeout"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfTimeout);
            packOperationTable["MembersCountReady"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMembersCountReady);
            packOperationTable["MembersCountTotal"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.ReadyVerificationRequestDto>(this.PackValueOfMembersCountTotal);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.ReadyVerificationRequestDto, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.ReadyVerificationRequestDto, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.ReadyVerificationRequestDto, bool>>(2);
            nullCheckerTable["Members"] = new System.Func<Stormancer.Plugins.ReadyVerificationRequestDto, bool>(this.IsMembersNull);
            nullCheckerTable["MatchId"] = new System.Func<Stormancer.Plugins.ReadyVerificationRequestDto, bool>(this.IsMatchIdNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>[5];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMembers);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMatchId);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfTimeout);
            unpackOperationList[3] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMembersCountReady);
            unpackOperationList[4] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMembersCountTotal);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>>(5);
            unpackOperationTable["Members"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMembers);
            unpackOperationTable["MatchId"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMatchId);
            unpackOperationTable["Timeout"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfTimeout);
            unpackOperationTable["MembersCountReady"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMembersCountReady);
            unpackOperationTable["MembersCountTotal"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.ReadyVerificationRequestDto, int, int>(this.UnpackValueOfMembersCountTotal);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "Members",
                    "MatchId",
                    "Timeout",
                    "MembersCountReady",
                    "MembersCountTotal"};
            this.this_SetUnpackedValueOfMembersDelegate = new System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, System.Collections.Generic.Dictionary<string, int>>(this.SetUnpackedValueOfMembers);
            this.this_SetUnpackedValueOfMatchIdDelegate = new System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, string>(this.SetUnpackedValueOfMatchId);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfTimeoutDelegate = new System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, int>(this.SetUnpackedValueOfTimeout);
            this.MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, int>(MsgPack.Serialization.UnpackHelpers.UnpackInt32Value);
            this.this_SetUnpackedValueOfMembersCountReadyDelegate = new System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, int>(this.SetUnpackedValueOfMembersCountReady);
            this.this_SetUnpackedValueOfMembersCountTotalDelegate = new System.Action<Stormancer.Plugins.ReadyVerificationRequestDto, int>(this.SetUnpackedValueOfMembersCountTotal);
        }
        
        private void PackValueOfMembers(MsgPack.Packer packer, Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            this._serializer0.PackTo(packer, objectTree.Members);
        }
        
        private bool IsMembersNull(Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            return (objectTree.Members == null);
        }
        
        private void PackValueOfMatchId(MsgPack.Packer packer, Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            this._serializer1.PackTo(packer, objectTree.MatchId);
        }
        
        private bool IsMatchIdNull(Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            return (objectTree.MatchId == null);
        }
        
        private void PackValueOfTimeout(MsgPack.Packer packer, Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            this._serializer2.PackTo(packer, objectTree.Timeout);
        }
        
        private void PackValueOfMembersCountReady(MsgPack.Packer packer, Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            this._serializer2.PackTo(packer, objectTree.MembersCountReady);
        }
        
        private void PackValueOfMembersCountTotal(MsgPack.Packer packer, Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            this._serializer2.PackTo(packer, objectTree.MembersCountTotal);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.ReadyVerificationRequestDto objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.ReadyVerificationRequestDto> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.ReadyVerificationRequestDto>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.ReadyVerificationRequestDto> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.ReadyVerificationRequestDto>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfMembers(Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, System.Collections.Generic.Dictionary<string, int> unpackedValue) {
            unpackingContext.Members = unpackedValue;
        }
        
        private void UnpackValueOfMembers(MsgPack.Unpacker unpacker, Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, System.Collections.Generic.Dictionary<string, int>> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, System.Collections.Generic.Dictionary<string, int>>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(System.Collections.Generic.Dictionary<string, int>);
            unpackHelperParameters.MemberName = "Members";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = null;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfMembersDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfMatchId(Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, string unpackedValue) {
            unpackingContext.MatchId = unpackedValue;
        }
        
        private void UnpackValueOfMatchId(MsgPack.Unpacker unpacker, Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "MatchId";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfMatchIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfTimeout(Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int unpackedValue) {
            unpackingContext.Timeout = unpackedValue;
        }
        
        private void UnpackValueOfTimeout(MsgPack.Unpacker unpacker, Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, int> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, int>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer2;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(int);
            unpackHelperParameters1.MemberName = "Timeout";
            unpackHelperParameters1.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfTimeoutDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters1);
        }
        
        private void SetUnpackedValueOfMembersCountReady(Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int unpackedValue) {
            unpackingContext.MembersCountReady = unpackedValue;
        }
        
        private void UnpackValueOfMembersCountReady(MsgPack.Unpacker unpacker, Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, int> unpackHelperParameters2 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, int>);
            unpackHelperParameters2.Unpacker = unpacker;
            unpackHelperParameters2.UnpackingContext = unpackingContext;
            unpackHelperParameters2.Serializer = this._serializer2;
            unpackHelperParameters2.ItemsCount = itemsCount;
            unpackHelperParameters2.Unpacked = indexOfItem;
            unpackHelperParameters2.TargetObjectType = typeof(int);
            unpackHelperParameters2.MemberName = "MembersCountReady";
            unpackHelperParameters2.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate;
            unpackHelperParameters2.Setter = this.this_SetUnpackedValueOfMembersCountReadyDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters2);
        }
        
        private void SetUnpackedValueOfMembersCountTotal(Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int unpackedValue) {
            unpackingContext.MembersCountTotal = unpackedValue;
        }
        
        private void UnpackValueOfMembersCountTotal(MsgPack.Unpacker unpacker, Stormancer.Plugins.ReadyVerificationRequestDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, int> unpackHelperParameters3 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.ReadyVerificationRequestDto, int>);
            unpackHelperParameters3.Unpacker = unpacker;
            unpackHelperParameters3.UnpackingContext = unpackingContext;
            unpackHelperParameters3.Serializer = this._serializer2;
            unpackHelperParameters3.ItemsCount = itemsCount;
            unpackHelperParameters3.Unpacked = indexOfItem;
            unpackHelperParameters3.TargetObjectType = typeof(int);
            unpackHelperParameters3.MemberName = "MembersCountTotal";
            unpackHelperParameters3.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackInt32ValueDelegate;
            unpackHelperParameters3.Setter = this.this_SetUnpackedValueOfMembersCountTotalDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters3);
        }
        
        protected internal override Stormancer.Plugins.ReadyVerificationRequestDto UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.ReadyVerificationRequestDto result = default(Stormancer.Plugins.ReadyVerificationRequestDto);
            result = new Stormancer.Plugins.ReadyVerificationRequestDto();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.ReadyVerificationRequestDto>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.ReadyVerificationRequestDto>(), this._unpackOperationTable);
            }
        }
    }
}

