//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_FriendStatusSerializer : MsgPack.Serialization.EnumMessagePackSerializer<Stormancer.Plugins.FriendStatus> {
        
        public Stormancer_Plugins_FriendStatusSerializer(MsgPack.Serialization.SerializationContext context) : 
                this(context, MsgPack.Serialization.EnumSerializationMethod.ByName) {
        }
        
        public Stormancer_Plugins_FriendStatusSerializer(MsgPack.Serialization.SerializationContext context, MsgPack.Serialization.EnumSerializationMethod enumSerializationMethod) : 
                base(context, enumSerializationMethod) {
        }
        
        protected internal override void PackUnderlyingValueTo(MsgPack.Packer packer, Stormancer.Plugins.FriendStatus enumValue) {
            packer.Pack(((int)(enumValue)));
        }
        
        protected internal override Stormancer.Plugins.FriendStatus UnpackFromUnderlyingValue(MsgPack.MessagePackObject messagePackObject) {
            return ((Stormancer.Plugins.FriendStatus)(messagePackObject.AsInt32()));
        }
    }
}

