//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Stormancer_Plugins_EndGameDtoSerializer : MsgPack.Serialization.MessagePackSerializer<Stormancer.Plugins.EndGameDto> {
        
        private MsgPack.Serialization.MessagePackSerializer<long> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer1;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Stormancer.Plugins.EndGameDto, bool>> _nullCheckersTable;
        
        private System.Action<Stormancer.Plugins.EndGameDto, long> this_SetUnpackedValueOfScoreDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, long> MsgPack_Serialization_UnpackHelpers_UnpackInt64ValueDelegate;
        
        private System.Action<Stormancer.Plugins.EndGameDto, string> this_SetUnpackedValueOfLeaderboardNameDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>> _unpackOperationTable;
        
        public Stormancer_Plugins_EndGameDtoSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<long>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<string>(schema1);
            System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>[] packOperationList = default(System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>[]);
            packOperationList = new System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>[2];
            packOperationList[0] = new System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>(this.PackValueOfScore);
            packOperationList[1] = new System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>(this.PackValueOfLeaderboardName);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>>(2);
            packOperationTable["Score"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>(this.PackValueOfScore);
            packOperationTable["LeaderboardName"] = new System.Action<MsgPack.Packer, Stormancer.Plugins.EndGameDto>(this.PackValueOfLeaderboardName);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.EndGameDto, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.EndGameDto, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Stormancer.Plugins.EndGameDto, bool>>(1);
            nullCheckerTable["LeaderboardName"] = new System.Func<Stormancer.Plugins.EndGameDto, bool>(this.IsLeaderboardNameNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>[2];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>(this.UnpackValueOfScore);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>(this.UnpackValueOfLeaderboardName);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>>(2);
            unpackOperationTable["Score"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>(this.UnpackValueOfScore);
            unpackOperationTable["LeaderboardName"] = new System.Action<MsgPack.Unpacker, Stormancer.Plugins.EndGameDto, int, int>(this.UnpackValueOfLeaderboardName);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "Score",
                    "LeaderboardName"};
            this.this_SetUnpackedValueOfScoreDelegate = new System.Action<Stormancer.Plugins.EndGameDto, long>(this.SetUnpackedValueOfScore);
            this.MsgPack_Serialization_UnpackHelpers_UnpackInt64ValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, long>(MsgPack.Serialization.UnpackHelpers.UnpackInt64Value);
            this.this_SetUnpackedValueOfLeaderboardNameDelegate = new System.Action<Stormancer.Plugins.EndGameDto, string>(this.SetUnpackedValueOfLeaderboardName);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
        }
        
        private void PackValueOfScore(MsgPack.Packer packer, Stormancer.Plugins.EndGameDto objectTree) {
            this._serializer0.PackTo(packer, objectTree.Score);
        }
        
        private void PackValueOfLeaderboardName(MsgPack.Packer packer, Stormancer.Plugins.EndGameDto objectTree) {
            this._serializer1.PackTo(packer, objectTree.LeaderboardName);
        }
        
        private bool IsLeaderboardNameNull(Stormancer.Plugins.EndGameDto objectTree) {
            return (objectTree.LeaderboardName == null);
        }
        
        protected internal override void PackToCore(MsgPack.Packer packer, Stormancer.Plugins.EndGameDto objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.EndGameDto> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Stormancer.Plugins.EndGameDto>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.EndGameDto> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Stormancer.Plugins.EndGameDto>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfScore(Stormancer.Plugins.EndGameDto unpackingContext, long unpackedValue) {
            unpackingContext.Score = unpackedValue;
        }
        
        private void UnpackValueOfScore(MsgPack.Unpacker unpacker, Stormancer.Plugins.EndGameDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.EndGameDto, long> unpackHelperParameters = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Stormancer.Plugins.EndGameDto, long>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(long);
            unpackHelperParameters.MemberName = "Score";
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackInt64ValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfScoreDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfLeaderboardName(Stormancer.Plugins.EndGameDto unpackingContext, string unpackedValue) {
            unpackingContext.LeaderboardName = unpackedValue;
        }
        
        private void UnpackValueOfLeaderboardName(MsgPack.Unpacker unpacker, Stormancer.Plugins.EndGameDto unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.EndGameDto, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Stormancer.Plugins.EndGameDto, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "LeaderboardName";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfLeaderboardNameDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        protected internal override Stormancer.Plugins.EndGameDto UnpackFromCore(MsgPack.Unpacker unpacker) {
            Stormancer.Plugins.EndGameDto result = default(Stormancer.Plugins.EndGameDto);
            result = new Stormancer.Plugins.EndGameDto();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.EndGameDto>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Stormancer.Plugins.EndGameDto>(), this._unpackOperationTable);
            }
        }
    }
}

